name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby 2.2.6
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby2.2 ruby2.2-dev
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build -d docs
