name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create docs folder
        run: |
          gem install jekyll bundler
          bundle install
          jekyll build -d docs
