name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@latest-version-here
        with:
          ruby-version: 3.0.0

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build Jekyll site
        run: jekyll build -d docs
